# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module PinpointEmail
      # Resource Type definition for AWS::PinpointEmail::DedicatedIpPool
      class DedicatedIpPool < ResourceType
        # Property Definition Tags
        class Tags < PropertyType
          #   @param [String|JSONable] value
          #     The value to use for Value
          def Value(value)
            dsl_attribute(:Value, value)
          end

          #   @param [String|JSONable] value
          #     The value to use for Key
          def Key(value)
            dsl_attribute(:Key, value)
          end
        end

        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for PoolName
        def PoolName(value)
          dsl_attribute(:PoolName, value)
        end

        # @param [Array<Tags>|JSONable>] values
        #   The List of values to use for Tags
        def Tags(values)
          dsl_list_attribute(:Tags, values)
        end

        #  @param [Tags|JSONable] value  Append value to the List
        #    The List of values to use for Tags
        # @@overload Tag(&block)
        # Append value to the List from block via instance eval of a new Tags
        def Tag(value = nil, fn_if: nil, **value_hash, &block)
          dsl_push_attribute(:Tags, value, fn_if: fn_if, attr_class: Tags, **value_hash, &block)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::PinpointEmail::DedicatedIpPool]
    def AWS_PinpointEmail_DedicatedIpPool(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::PinpointEmail::DedicatedIpPool, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
