# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module CloudFormation
      # Resource Type definition for AWS::CloudFormation::WaitConditionHandle
      class WaitConditionHandle < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::CloudFormation::WaitConditionHandle]
    def AWS_CloudFormation_WaitConditionHandle(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::CloudFormation::WaitConditionHandle, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
