# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module RoboMaker
      # Resource Type definition for AWS::RoboMaker::Robot
      class Robot < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Fleet
        def Fleet(value)
          dsl_attribute(:Fleet, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Architecture
        def Architecture(value)
          dsl_attribute(:Architecture, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for GreengrassGroupId
        def GreengrassGroupId(value)
          dsl_attribute(:GreengrassGroupId, value)
        end

        #   @param [Object|JSONable] value
        #     The value to use for Tags
        def Tags(value)
          dsl_attribute(:Tags, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Name
        def Name(value)
          dsl_attribute(:Name, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::RoboMaker::Robot]
    def AWS_RoboMaker_Robot(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::RoboMaker::Robot, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
