# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module Pinpoint
      # Resource Type definition for AWS::Pinpoint::SmsTemplate
      class SmsTemplate < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for TemplateName
        def TemplateName(value)
          dsl_attribute(:TemplateName, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for TemplateDescription
        def TemplateDescription(value)
          dsl_attribute(:TemplateDescription, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for DefaultSubstitutions
        def DefaultSubstitutions(value)
          dsl_attribute(:DefaultSubstitutions, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Arn
        def Arn(value)
          dsl_attribute(:Arn, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Body
        def Body(value)
          dsl_attribute(:Body, value)
        end

        #   @param [Object|JSONable] value
        #     The value to use for Tags
        def Tags(value)
          dsl_attribute(:Tags, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::Pinpoint::SmsTemplate]
    def AWS_Pinpoint_SmsTemplate(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::Pinpoint::SmsTemplate, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
