# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module AppStream
      # Resource Type definition for AWS::AppStream::StackFleetAssociation
      class StackFleetAssociation < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for FleetName
        def FleetName(value)
          dsl_attribute(:FleetName, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for StackName
        def StackName(value)
          dsl_attribute(:StackName, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::AppStream::StackFleetAssociation]
    def AWS_AppStream_StackFleetAssociation(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::AppStream::StackFleetAssociation, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
