# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module ImageBuilder
      # Resource schema for AWS::ImageBuilder::DistributionConfiguration
      # @see https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-imagebuilder.git
      class DistributionConfiguration < ResourceType
        # The distributions of the distribution configuration.
        class Distribution < PropertyType
          #   @param [String|JSONable] value
          #     region
          def Region(value)
            dsl_attribute(:Region, value)
          end

          #   @param [Object|JSONable] value
          #     The specific AMI settings (for example, launch permissions, AMI tags).
          def AmiDistributionConfiguration(value)
            dsl_attribute(:AmiDistributionConfiguration, value)
          end

          # @param [Array<String>|JSONable>] values
          #   The License Manager Configuration to associate with the AMI in the specified Region.
          def LicenseConfigurationArns(values)
            dsl_list_attribute(:LicenseConfigurationArns, values)
          end

          #  @param [String|JSONable] value  Append value to the List
          #    The License Manager Configuration to associate with the AMI in the specified Region.
          def LicenseConfigurationArn(value, fn_if: nil)
            dsl_push_attribute(:LicenseConfigurationArns, value, fn_if: fn_if)
          end
        end

        #   @param [String|JSONable] value
        #     The Amazon Resource Name (ARN) of the distribution configuration.
        def Arn(value)
          dsl_attribute(:Arn, value)
        end

        #   @param [String|JSONable] value
        #     The name of the distribution configuration.
        def Name(value)
          dsl_attribute(:Name, value)
        end

        #   @param [String|JSONable] value
        #     The description of the distribution configuration.
        def Description(value)
          dsl_attribute(:Description, value)
        end

        # @param [Array<Distribution>|JSONable>] values
        #   The distributions of the distribution configuration.
        def Distributions(values)
          dsl_list_attribute(:Distributions, values)
        end

        #  @param [Distribution|JSONable] value  Append value to the List
        #    The distributions of the distribution configuration.
        # @@overload Distribution(&block)
        # Append value to the List from block via instance eval of a new Distribution
        def Distribution(value = nil, fn_if: nil, **value_hash, &block)
          dsl_push_attribute(:Distributions, value, fn_if: fn_if, attr_class: Distribution, **value_hash, &block)
        end

        #   @param [Object|JSONable] value
        #     The tags associated with the component.
        def Tags(value)
          dsl_attribute(:Tags, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::ImageBuilder::DistributionConfiguration]
    def AWS_ImageBuilder_DistributionConfiguration(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::ImageBuilder::DistributionConfiguration, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
