# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module ServiceCatalog
      # Resource Type definition for AWS::ServiceCatalog::LaunchTemplateConstraint
      class LaunchTemplateConstraint < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Description
        def Description(value)
          dsl_attribute(:Description, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for AcceptLanguage
        def AcceptLanguage(value)
          dsl_attribute(:AcceptLanguage, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for PortfolioId
        def PortfolioId(value)
          dsl_attribute(:PortfolioId, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for ProductId
        def ProductId(value)
          dsl_attribute(:ProductId, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Rules
        def Rules(value)
          dsl_attribute(:Rules, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::ServiceCatalog::LaunchTemplateConstraint]
    def AWS_ServiceCatalog_LaunchTemplateConstraint(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::ServiceCatalog::LaunchTemplateConstraint, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
