# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module EC2
      # Describes a route for a local gateway route table.
      # @see https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2-lgw.git
      class LocalGatewayRoute < ResourceType
        #   @param [String|JSONable] value
        #     The CIDR block used for destination matches.
        def DestinationCidrBlock(value)
          dsl_attribute(:DestinationCidrBlock, value)
        end

        #   @param [String|JSONable] value
        #     The ID of the local gateway route table.
        def LocalGatewayRouteTableId(value)
          dsl_attribute(:LocalGatewayRouteTableId, value)
        end

        #   @param [String|JSONable] value
        #     The ID of the virtual interface group.
        def LocalGatewayVirtualInterfaceGroupId(value)
          dsl_attribute(:LocalGatewayVirtualInterfaceGroupId, value)
        end

        #   @param [String|JSONable] value
        #     The state of the route.
        def State(value)
          dsl_attribute(:State, value)
        end

        #   @param [String|JSONable] value
        #     The route type.
        def Type(value)
          dsl_attribute(:Type, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::EC2::LocalGatewayRoute]
    def AWS_EC2_LocalGatewayRoute(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::EC2::LocalGatewayRoute, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
