# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module EC2
      # Resource Type definition for AWS::EC2::VPCCidrBlock
      class VPCCidrBlock < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [Boolean|JSONable] value
        #     The value to use for AmazonProvidedIpv6CidrBlock
        def AmazonProvidedIpv6CidrBlock(value)
          dsl_attribute(:AmazonProvidedIpv6CidrBlock, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for CidrBlock
        def CidrBlock(value)
          dsl_attribute(:CidrBlock, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for VpcId
        def VpcId(value)
          dsl_attribute(:VpcId, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::EC2::VPCCidrBlock]
    def AWS_EC2_VPCCidrBlock(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::EC2::VPCCidrBlock, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
