# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module IoT
      # Resource Type definition for AWS::IoT::Thing
      class Thing < ResourceType
        # Property Definition AttributePayload
        class AttributePayload < PropertyType
          #   @param [Object|JSONable] value
          #     The value to use for Attributes
          def Attributes(value)
            dsl_attribute(:Attributes, value)
          end
        end

        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [AttributePayload|JSONable] value
        #     The value to use for AttributePayload
        # @@overload AttributePayload(&block)
        #   Set :AttributePayload from block via instance eval of a new AttributePayload
        def AttributePayload(value = nil, **value_hash, &block)
          dsl_attribute(:AttributePayload, value, attr_class: AttributePayload, **value_hash, &block)
        end

        #   @param [String|JSONable] value
        #     The value to use for ThingName
        def ThingName(value)
          dsl_attribute(:ThingName, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::IoT::Thing]
    def AWS_IoT_Thing(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::IoT::Thing, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
