# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module Config
      # Resource Type definition for AWS::Config::RemediationConfiguration
      class RemediationConfiguration < ResourceType
        # Property Definition ExecutionControls
        class ExecutionControls < PropertyType
          #   @param [SsmControls|JSONable] value
          #     The value to use for SsmControls
          # @@overload SsmControls(&block)
          #   Set :SsmControls from block via instance eval of a new SsmControls
          def SsmControls(value = nil, **value_hash, &block)
            dsl_attribute(:SsmControls, value, attr_class: SsmControls, **value_hash, &block)
          end
        end

        # Property Definition SsmControls
        class SsmControls < PropertyType
          #   @param [Integer|JSONable] value
          #     The value to use for ErrorPercentage
          def ErrorPercentage(value)
            dsl_attribute(:ErrorPercentage, value)
          end

          #   @param [Integer|JSONable] value
          #     The value to use for ConcurrentExecutionRatePercentage
          def ConcurrentExecutionRatePercentage(value)
            dsl_attribute(:ConcurrentExecutionRatePercentage, value)
          end
        end

        #   @param [String|JSONable] value
        #     The value to use for TargetVersion
        def TargetVersion(value)
          dsl_attribute(:TargetVersion, value)
        end

        #   @param [ExecutionControls|JSONable] value
        #     The value to use for ExecutionControls
        # @@overload ExecutionControls(&block)
        #   Set :ExecutionControls from block via instance eval of a new ExecutionControls
        def ExecutionControls(value = nil, **value_hash, &block)
          dsl_attribute(:ExecutionControls, value, attr_class: ExecutionControls, **value_hash, &block)
        end

        #   @param [Object|JSONable] value
        #     The value to use for Parameters
        def Parameters(value)
          dsl_attribute(:Parameters, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for TargetType
        def TargetType(value)
          dsl_attribute(:TargetType, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for ConfigRuleName
        def ConfigRuleName(value)
          dsl_attribute(:ConfigRuleName, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for ResourceType
        def ResourceType(value)
          dsl_attribute(:ResourceType, value)
        end

        #   @param [Integer|JSONable] value
        #     The value to use for RetryAttemptSeconds
        def RetryAttemptSeconds(value)
          dsl_attribute(:RetryAttemptSeconds, value)
        end

        #   @param [Integer|JSONable] value
        #     The value to use for MaximumAutomaticAttempts
        def MaximumAutomaticAttempts(value)
          dsl_attribute(:MaximumAutomaticAttempts, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for TargetId
        def TargetId(value)
          dsl_attribute(:TargetId, value)
        end

        #   @param [Boolean|JSONable] value
        #     The value to use for Automatic
        def Automatic(value)
          dsl_attribute(:Automatic, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::Config::RemediationConfiguration]
    def AWS_Config_RemediationConfiguration(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::Config::RemediationConfiguration, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
