# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module ApiGateway
      # Resource Type definition for AWS::ApiGateway::GatewayResponse
      class GatewayResponse < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [Object|JSONable] value
        #     The value to use for ResponseParameters
        def ResponseParameters(value)
          dsl_attribute(:ResponseParameters, value)
        end

        #   @param [Object|JSONable] value
        #     The value to use for ResponseTemplates
        def ResponseTemplates(value)
          dsl_attribute(:ResponseTemplates, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for ResponseType
        def ResponseType(value)
          dsl_attribute(:ResponseType, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for RestApiId
        def RestApiId(value)
          dsl_attribute(:RestApiId, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for StatusCode
        def StatusCode(value)
          dsl_attribute(:StatusCode, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::ApiGateway::GatewayResponse]
    def AWS_ApiGateway_GatewayResponse(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::ApiGateway::GatewayResponse, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
