# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module ApiGateway
      # Resource Type definition for AWS::ApiGateway::RequestValidator
      class RequestValidator < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Name
        def Name(value)
          dsl_attribute(:Name, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for RestApiId
        def RestApiId(value)
          dsl_attribute(:RestApiId, value)
        end

        #   @param [Boolean|JSONable] value
        #     The value to use for ValidateRequestBody
        def ValidateRequestBody(value)
          dsl_attribute(:ValidateRequestBody, value)
        end

        #   @param [Boolean|JSONable] value
        #     The value to use for ValidateRequestParameters
        def ValidateRequestParameters(value)
          dsl_attribute(:ValidateRequestParameters, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::ApiGateway::RequestValidator]
    def AWS_ApiGateway_RequestValidator(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::ApiGateway::RequestValidator, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
