# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module Lambda
      # Resource Type definition for AWS::Lambda::LayerVersionPermission
      class LayerVersionPermission < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Action
        def Action(value)
          dsl_attribute(:Action, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for LayerVersionArn
        def LayerVersionArn(value)
          dsl_attribute(:LayerVersionArn, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for OrganizationId
        def OrganizationId(value)
          dsl_attribute(:OrganizationId, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Principal
        def Principal(value)
          dsl_attribute(:Principal, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::Lambda::LayerVersionPermission]
    def AWS_Lambda_LayerVersionPermission(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::Lambda::LayerVersionPermission, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
