# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module Lambda
      # Resource Type definition for AWS::Lambda::Permission
      class Permission < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Action
        def Action(value)
          dsl_attribute(:Action, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for EventSourceToken
        def EventSourceToken(value)
          dsl_attribute(:EventSourceToken, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for FunctionName
        def FunctionName(value)
          dsl_attribute(:FunctionName, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Principal
        def Principal(value)
          dsl_attribute(:Principal, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for SourceAccount
        def SourceAccount(value)
          dsl_attribute(:SourceAccount, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for SourceArn
        def SourceArn(value)
          dsl_attribute(:SourceArn, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::Lambda::Permission]
    def AWS_Lambda_Permission(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::Lambda::Permission, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
