# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module ElastiCache
      # Resource Type definition for AWS::ElastiCache::SecurityGroupIngress
      class SecurityGroupIngress < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for CacheSecurityGroupName
        def CacheSecurityGroupName(value)
          dsl_attribute(:CacheSecurityGroupName, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for EC2SecurityGroupName
        def EC2SecurityGroupName(value)
          dsl_attribute(:EC2SecurityGroupName, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for EC2SecurityGroupOwnerId
        def EC2SecurityGroupOwnerId(value)
          dsl_attribute(:EC2SecurityGroupOwnerId, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::ElastiCache::SecurityGroupIngress]
    def AWS_ElastiCache_SecurityGroupIngress(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::ElastiCache::SecurityGroupIngress, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
