# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module Glue
      # This resource adds Key-Value metadata to a Schema version of Glue Schema Registry.
      # @see https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-glue.git
      class SchemaVersionMetadata < ResourceType
        #   @param [String|JSONable] value
        #     Represents the version ID associated with the schema version.
        def SchemaVersionId(value)
          dsl_attribute(:SchemaVersionId, value)
        end

        #   @param [String|JSONable] value
        #     Metadata key
        def Key(value)
          dsl_attribute(:Key, value)
        end

        #   @param [String|JSONable] value
        #     Metadata value
        def Value(value)
          dsl_attribute(:Value, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::Glue::SchemaVersionMetadata]
    def AWS_Glue_SchemaVersionMetadata(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::Glue::SchemaVersionMetadata, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
