# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module OpsWorks
      # Resource Type definition for AWS::OpsWorks::UserProfile
      class UserProfile < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for SshUsername
        def SshUsername(value)
          dsl_attribute(:SshUsername, value)
        end

        #   @param [Boolean|JSONable] value
        #     The value to use for AllowSelfManagement
        def AllowSelfManagement(value)
          dsl_attribute(:AllowSelfManagement, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for IamUserArn
        def IamUserArn(value)
          dsl_attribute(:IamUserArn, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for SshPublicKey
        def SshPublicKey(value)
          dsl_attribute(:SshPublicKey, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::OpsWorks::UserProfile]
    def AWS_OpsWorks_UserProfile(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::OpsWorks::UserProfile, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
