# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require_relative 'io_t_analytics/channel'
require_relative 'io_t_analytics/dataset'
require_relative 'io_t_analytics/datastore'
require_relative 'io_t_analytics/pipeline'
