# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require_relative 'kinesis_analytics/application'
require_relative 'kinesis_analytics/application_output'
require_relative 'kinesis_analytics/application_reference_data_source'
