# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require_relative 'logs/destination'
require_relative 'logs/log_group'
require_relative 'logs/log_stream'
require_relative 'logs/metric_filter'
require_relative 'logs/subscription_filter'
