# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require_relative 'network_manager/customer_gateway_association'
require_relative 'network_manager/device'
require_relative 'network_manager/global_network'
require_relative 'network_manager/link'
require_relative 'network_manager/link_association'
require_relative 'network_manager/site'
require_relative 'network_manager/transit_gateway_registration'
