# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module Events
      # Resource Type definition for AWS::Events::Archive
      class Archive < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for ArchiveName
        def ArchiveName(value)
          dsl_attribute(:ArchiveName, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for SourceArn
        def SourceArn(value)
          dsl_attribute(:SourceArn, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Description
        def Description(value)
          dsl_attribute(:Description, value)
        end

        #   @param [Object|JSONable] value
        #     The value to use for EventPattern
        def EventPattern(value)
          dsl_attribute(:EventPattern, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Arn
        def Arn(value)
          dsl_attribute(:Arn, value)
        end

        #   @param [Integer|JSONable] value
        #     The value to use for RetentionDays
        def RetentionDays(value)
          dsl_attribute(:RetentionDays, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::Events::Archive]
    def AWS_Events_Archive(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::Events::Archive, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
