# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module IAM
      # Resource Type definition for AWS::IAM::UserToGroupAddition
      class UserToGroupAddition < ResourceType
        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for GroupName
        def GroupName(value)
          dsl_attribute(:GroupName, value)
        end

        # @param [Array<String>|JSONable>] values
        #   The List of values to use for Users
        def Users(values)
          dsl_list_attribute(:Users, values)
        end

        #  @param [String|JSONable] value  Append value to the List
        #    The List of values to use for Users
        def User(value, fn_if: nil)
          dsl_push_attribute(:Users, value, fn_if: fn_if)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::IAM::UserToGroupAddition]
    def AWS_IAM_UserToGroupAddition(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::IAM::UserToGroupAddition, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
