# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated by CfnDsl::Generate
#
# WARNING ABOUT GENERATED CODE
require 'cfndsl/cloudformation_template'
require 'cfndsl/types'

module CfnDsl
  module AWS
    module IAM
      # Resource Type definition for AWS::IAM::User
      class User < ResourceType
        # Property Definition Policy
        class Policy < PropertyType
          #   @param [Object|JSONable] value
          #     The value to use for PolicyDocument
          def PolicyDocument(value)
            dsl_attribute(:PolicyDocument, value)
          end

          #   @param [String|JSONable] value
          #     The value to use for PolicyName
          def PolicyName(value)
            dsl_attribute(:PolicyName, value)
          end
        end

        # Property Definition Tag
        class Tag < PropertyType
          #   @param [String|JSONable] value
          #     The value to use for Value
          def Value(value)
            dsl_attribute(:Value, value)
          end

          #   @param [String|JSONable] value
          #     The value to use for Key
          def Key(value)
            dsl_attribute(:Key, value)
          end
        end

        # Property Definition LoginProfile
        class LoginProfile < PropertyType
          #   @param [Boolean|JSONable] value
          #     The value to use for PasswordResetRequired
          def PasswordResetRequired(value)
            dsl_attribute(:PasswordResetRequired, value)
          end

          #   @param [String|JSONable] value
          #     The value to use for Password
          def Password(value)
            dsl_attribute(:Password, value)
          end
        end

        #   @param [String|JSONable] value
        #     The value to use for Path
        def Path(value)
          dsl_attribute(:Path, value)
        end

        # @param [Array<String>|JSONable>] values
        #   The List of values to use for ManagedPolicyArns
        def ManagedPolicyArns(values)
          dsl_list_attribute(:ManagedPolicyArns, values)
        end

        #  @param [String|JSONable] value  Append value to the List
        #    The List of values to use for ManagedPolicyArns
        def ManagedPolicyArn(value, fn_if: nil)
          dsl_push_attribute(:ManagedPolicyArns, value, fn_if: fn_if)
        end

        # @param [Array<Policy>|JSONable>] values
        #   The List of values to use for Policies
        def Policies(values)
          dsl_list_attribute(:Policies, values)
        end

        #  @param [Policy|JSONable] value  Append value to the List
        #    The List of values to use for Policies
        # @@overload Policy(&block)
        # Append value to the List from block via instance eval of a new Policy
        def Policy(value = nil, fn_if: nil, **value_hash, &block)
          dsl_push_attribute(:Policies, value, fn_if: fn_if, attr_class: Policy, **value_hash, &block)
        end

        #   @param [String|JSONable] value
        #     The value to use for UserName
        def UserName(value)
          dsl_attribute(:UserName, value)
        end

        # @param [Array<String>|JSONable>] values
        #   The List of values to use for Groups
        def Groups(values)
          dsl_list_attribute(:Groups, values)
        end

        #  @param [String|JSONable] value  Append value to the List
        #    The List of values to use for Groups
        def Group(value, fn_if: nil)
          dsl_push_attribute(:Groups, value, fn_if: fn_if)
        end

        #   @param [String|JSONable] value
        #     The value to use for Id
        def Id(value)
          dsl_attribute(:Id, value)
        end

        #   @param [String|JSONable] value
        #     The value to use for Arn
        def Arn(value)
          dsl_attribute(:Arn, value)
        end

        #   @param [LoginProfile|JSONable] value
        #     The value to use for LoginProfile
        # @@overload LoginProfile(&block)
        #   Set :LoginProfile from block via instance eval of a new LoginProfile
        def LoginProfile(value = nil, **value_hash, &block)
          dsl_attribute(:LoginProfile, value, attr_class: LoginProfile, **value_hash, &block)
        end

        # @param [Array<Tag>|JSONable>] values
        #   The List of values to use for Tags
        def Tags(values)
          dsl_list_attribute(:Tags, values)
        end

        #  @param [Tag|JSONable] value  Append value to the List
        #    The List of values to use for Tags
        # @@overload Tag(&block)
        # Append value to the List from block via instance eval of a new Tag
        def Tag(value = nil, fn_if: nil, **value_hash, &block)
          dsl_push_attribute(:Tags, value, fn_if: fn_if, attr_class: Tag, **value_hash, &block)
        end

        #   @param [String|JSONable] value
        #     The value to use for PermissionsBoundary
        def PermissionsBoundary(value)
          dsl_attribute(:PermissionsBoundary, value)
        end
      end
    end
  end

  # rubocop:disable Style/Documentation
  class CloudFormationTemplate
    # @return [AWS::IAM::User]
    def AWS_IAM_User(logical_id, value = nil, &block)
      Resource(logical_id, value, attr_class: AWS::IAM::User, &block)
    end
  end

  # rubocop:enable Style/Documentation
end
